// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwSHAMIQJppIjMqPRgzChbDk1EfkefwPI',
    appId: '1:782362937400:web:fbbbba9336c2c998adbecd',
    messagingSenderId: '782362937400',
    projectId: 'tournament-app-b1764',
    authDomain: 'tournament-app-b1764.firebaseapp.com',
    storageBucket: 'tournament-app-b1764.firebasestorage.app',
    measurementId: 'G-98SJSVE9N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwX1yq1FebYvn8lXfjwL-3wYcEw7Le1ZM',
    appId: '1:782362937400:android:a9a6fce3edd51da0adbecd',
    messagingSenderId: '782362937400',
    projectId: 'tournament-app-b1764',
    storageBucket: 'tournament-app-b1764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC74p-3PIuTmm1AEiQ4b-zulbAibHOr_Ag',
    appId: '1:782362937400:ios:3b76e8ffc99fa5f5adbecd',
    messagingSenderId: '782362937400',
    projectId: 'tournament-app-b1764',
    storageBucket: 'tournament-app-b1764.firebasestorage.app',
    iosClientId: '782362937400-5o2rc71jgbil6f6jugc128qidq9td8tf.apps.googleusercontent.com',
    iosBundleId: 'com.MobahasatKitab.tournament',
  );
}
